### ISSUE TITLE
This snippet is not working

### ISSUE THREAD

**Issue by mxschmitt** [lemaiwo/CustomControlGenerator#1]
First of all nice talk at the Track Play day in Walldorf :+1: 
This snippet is unfortunately not working, maybe you can take a look at it and fix it.
http://pastebin.com/adTdahnN
Thanks :)

**Comment by lemaiwo** [comment]
Hi, 
Thanks for the feedback!

Tried it myself and for me it works. I think you may have a previous version of the plugin which is coming from a cache. You should try opening F12 --> disable caching --> reload webide. If still having the problem we can always set up a skype meeting and look into it together ?

Kind regards,
Wouter

**Comment by lemaiwo** [comment]
Okey, found the issue. Put the wrong destination on git. It's the url to my test account. This should be the url https://htmltocontrolconverter-a6ac3f497.dispatcher.hana.ondemand.com

I'll update the git page

**Comment by lemaiwo** [comment]
Probably will have to clear cache because you've used an older version..

**Comment by mxschmitt** [comment]
Yep, thanks :+1: Now It is working without any error thanks :)

**Comment by lemaiwo** [comment]
Thanks for noticing! Any other feedback is always welcome!
